### ISSUE TITLE
Data not defined

### ISSUE THREAD

**Issue by droblue** [blakeporterneuro/steamMarket#1]
So within
# resave old version to new_2
data['maxMinIdxDiff'] = data['maxIdx'] - data['minIdx'];
combo2['maxMinIdxDiff'] = combo2['maxIdx'] - combo2['minIdx'];

data['OGNZAvgDiff'] = data['priceAvg']-data['OG_price_NZ'];

#data['OG_price'] = "";
#data['itemType'] = "";
#data['itemType'] = "";
data.to_pickle(gameID+'PriceData_master_priceFill.pkl');

data.to_excel('rustMarketMaster.xlsx');
priceVector.to_excel(gameID+'indexPrice.xlsx');
volItemNorm.to_excel(gameID+'indexVol.xlsx');
marketDelta.to_excel(gameID+'marketDelta.xlsx');

data.to_pickle(gameID+'PriceData_3.pkl');

marketPrice.to_pickle(gameID+'marketPrice.pkl');
marketVol.to_pickle(gameID+'marketVol.pkl');
marketDelta.to_pickle(gameID+'marketDelta.pkl');

# add in new columns to master
data = data.set_index('itemName');
combo['itemName'] = combo['itemName'].str.lower();

combo2 = combo2.set_index('itemName');
new = combo['smoothChange'];

data['smoothChange'] = new;

test = data.merge(combo2,how='left');

test = combo2[combo2['priceIncrease'] < -100]

data = pd.concat([data, test]);
there seems to be a problem right here as it gives off the error
NameError: name 'data' is not defined
within the first line of the code (shown below)
data['maxMinIdxDiff'] = data['maxIdx'] - data['minIdx']
So i merely copied and pasted your code but it does not seem to working so I was wondering what this part of the code meant as it seemed to the issue with why the data analysis file was not working

**Comment by blakeporterneuro** [comment]
My apologies I should have been clearer in the documentation. 
**steamMarket_dataAnalysis** assumes you have ran **steamMarket_dataCollection**.

If you are running them different session you need to load in the data first before doing anything in **steamMarket_dataAnalysis**. This is done with the code the the last part (Step 3) of  **steamMarket_dataCollection**.

```
gameID = '578080';
# open file with all names
with open(gameID+'PriceData.pkl', "rb") as file:   # Unpickling
   data = pickle.load(file)
```

**Comment by blakeporterneuro** [comment]
And actually, a lot of that code you are referencing is a lot of random clean up and niche analysis I needed. I've taken it out of the current master. If you don't know what it is doing, you probably don't need it. 

The analysis program is much more of a template and I would encourage you to go through it for what you need, as it has some specificity that will only work for the game Rust.
